AgendaWeb/AgendaWeb/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using AgendaWeb.Models;

namespace AgendaWeb.Controllers
{
    public class AgendaController : Controller
    {
        private AgendaEntities db = new AgendaEntities();

        public ActionResult enviarMensaje(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        public ActionResult Correo()
        {
            ViewBag.enviado="Se ha enviado el correo exitosamente";
            var agenda = db.Agenda.Include(a => a.Usuario);
            int uid = (int)Session["UserID"];

            agenda = agenda.Where(a => a.idUsuario == uid);

            return View("Index",agenda.ToList());
        }

        // GET: Agenda
        public ActionResult Index()
        {
            var agenda = db.Agenda.Include(a => a.Usuario);
            return View(agenda.ToList());
        }

        [HttpPost]
        public ActionResult Index(string nombreContacto)
        {
            var contactos = from tabla in db.Agenda select tabla;
            int uid = (int)Session["UserID"];
            if (!String.IsNullOrEmpty(nombreContacto))
            {
                contactos = contactos.Where(tabla => tabla.nombreContacto.Contains(nombreContacto) && tabla.idUsuario==uid);
            }
            else
            {
                return RedirectToAction("verAgenda");
            }

            return View(contactos.ToList());
        }

        public ActionResult verAgenda(/*int? mid*/)
        {
            if (Session["UserID"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            int uid = (int)Session["UserID"];
            var agenda = db.Agenda.Where(a => a.idUsuario == uid /*&& a.Materia_ID == mid*/).ToList();
            return View("Index", agenda);
        }

        // GET: Agenda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // GET: Agenda/Create
        public ActionResult Create()
        {
            ViewBag.idUsuario = new SelectList(db.Usuario, "id", "usuario1");
            return View();
        }

        // POST: Agenda/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,idUsuario,nombreContacto,telefono,email,direccion")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Agenda.Add(agenda);
                db.SaveChanges();
                return RedirectToAction("verAgenda");
            }

            ViewBag.idUsuario = new SelectList(db.Usuario, "id", "usuario1", agenda.idUsuario);
            return View(agenda);
        }

        // GET: Agenda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserID"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            int uid = (int)Session["UserID"];
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }

            List<SelectListItem> lst = new List<SelectListItem>();

            List<Agenda> m = db.Agenda.Where(d => d.idUsuario == uid).ToList();

            foreach (var s in m)
            {
                lst.Add(new SelectListItem() { Text = s.nombreContacto, Value = s.id.ToString() });
            }
            ViewBag.materias = lst;

            ViewBag.idUsuario = new SelectList(db.Usuario, "id", "usuario1", agenda.idUsuario);
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,idUsuario,nombreContacto,telefono,email,direccion")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agenda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("verAgenda");
            }
            ViewBag.idUsuario = new SelectList(db.Usuario, "id", "usuario1", agenda.idUsuario);
            return View(agenda);
        }

        // GET: Agenda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = db.Agenda.Find(id);
            if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agenda agenda = db.Agenda.Find(id);
            db.Agenda.Remove(agenda);
            db.SaveChanges();
            return RedirectToAction("verAgenda");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AgendaWeb/AgendaWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgendaWeb.Models;

namespace AgendaWeb.Controllers
{
    public class HomeController : Controller
    {
        private AgendaEntities db = new AgendaEntities();
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                int uid = (int)Session["UserID"];
                return View(db.Agenda.Where(m => m.idUsuario == uid).ToList());
            }
            return View();
        }

        [HttpPost]
        public ActionResult login(Usuario login)
        {
            if (db.Usuario.Where(n => n.usuario1 == login.usuario1 && n.password == login.password).ToList().Count > 0)
            {
                Usuario s = db.Usuario.Where(n => n.usuario1 == login.usuario1).First();
                Session["UserEmail"] = s.usuario1;
                Session["UserID"] = s.id;
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Error = "Usuario y/o Contraseña Incorrecta";
            }
            return View();
        }



        public ActionResult login()
        {
            return View();
        }

        public ActionResult logout()
        {

            Session.Clear();
            Session.Abandon();
            return RedirectToAction("login", "Home");
        }

        public ActionResult registrarse()
        {
            return View();
        }

        [HttpPost]
        public ActionResult registrarse([Bind(Include = "usuario1, password")] Usuario reg)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Usuario.Add(reg);
                    db.SaveChanges();

                    ViewBag.notificacion = "Usuario Registrado";
                    return View("login");
                }
            }
            catch (Exception ex)
            {
                ViewBag.notificacion = "El usuario ya existe";
            }
            //todo

            return View();
        }
    }
}

AgendaWeb/AgendaWeb/Views/Home/Index.cshtml
@model IEnumerable<AgendaWeb.Models.Agenda>
@using AgendaWeb.Models

@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    @if (ViewBag.notificacion != null)
    {
        <div class="notification is-success">
            @ViewBag.notificacion
        </div>
    }

    @if (Session["UserID"] != null)
    {

        int split = 3;
        int total = (int)Math.Ceiling((decimal)Model.Count() / split);

        <section class="section">
            <h1 class="title is-2 has-text-centered">Bienvenido  <br /><b>@Session["UserEmail"]</b></h1>
            <br />

            <h1 class="subtitle is-4 has-text-centered">¿Qué desea hacer?</h1>
            <div class="columns">
                <div class="column">
                    @Html.ActionLink("Agregar Contacto", "create", "Agenda", null, new { @class = "button is-primary is-fullwidth" })
                </div>
                <div class="column">
                    @Html.ActionLink("Ver Contactos", "verAgenda", "Agenda", null, new { @class = "button is-info is-fullwidth" })
                </div>
            </div>
            <hr />
            @for (int i = 0; i < total; i++)
            {
                <div class="columns">
                    @for (int q = 0; q < split; q++)
                    {
                        int current = (i * split) + q;
                        if (current > Model.Count() - 1)
                        {
                            <div class="column"></div>
                            continue;
                        }
                        <div class="column">
                            <div class="card">
                                <div class="card-content">
                                    <p class="title is-size-5 has-text-centered">Contacto</p>
                                    <p class="subtitle has-text-centered">
                                        @Model.ElementAt(current).nombreContacto
                                    </p>
                                </div>
                                <footer class="card-footer">
                                    <p class="card-footer-item">
                                        @Html.ActionLink("Detalles", "Details", "Agenda" , new { id = Model.ElementAt(current).id },null)
                                    </p>
                                    <p class="card-footer-item">
                                        @Html.ActionLink("Eliminar", "Delete", "Agenda", new { id = Model.ElementAt(current).id }, null)
                                    </p>
                                </footer>
                            </div>
                        </div>
                    }
                </div>
            }
        </section>

    }
</div>
@*<div class="jumbotron">
        <h1>Agenda de Contactos</h1>
        <p class="lead">En esta agenda puede dar mantenimiento a sus contactos</p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Message</h2>
            <p>
                #messagge
            </p>
        </div>
    </div>*@

AgendaWeb/AgendaWeb/Views/Home/login.cshtml
@model AgendaWeb.Models.Usuario


@{
    ViewBag.Title = "login";
}



<div class="container">
    <section class="section">
        @if (ViewBag.Error != null)
        {
            <div class="notification is-danger">
                @ViewBag.Error
            </div>
        }

        @if (ViewBag.notificacion != null)
        {
            <div class="notification is-success">
                @ViewBag.notificacion
            </div>
        }

        @if (Session["UserEmail"] == null)
        {
            <div class="columns is-centered">
                <div class="column is-one-third ">

                    <div class="card">
                        <div class="has-background-primary">
                            <p class="title has-text-white" style="padding:30px;">Login</p>
                        </div>
                        @using (Html.BeginForm("login", "home", FormMethod.Post))
                        {
                            <div class="card-content">
                                <div class="field">
                                    @Html.Label("Email", new { @class = "label", })
                                    <div class="control">
                                        @Html.EditorFor(Model => Model.usuario1, new { htmlAttributes = new { @class = "input", @type = "email" } })
                                    </div>
                                </div>

                                <div class="field">
                                    @Html.Label("Contraseña", new { @class = "label" })
                                    <div class="control">
                                        @Html.EditorFor(Model => Model.password, new { htmlAttributes = new { @class = "input", @type = "password" } })
                                    </div>
                                </div>


                                <div class="field">
                                    <div class="columns">
                                        <div class="column">
                                            <div class="control">
                                                <button value="submit" name="submit" class="button is-primary is-fullwidth">Iniciar Sesion</button>

                                            </div>
                                        </div>
                                        <div class="column">
                                            <div class="control">
                                                @Html.ActionLink("Registrarse", "registrarse", null, new { @class = "button is-fullwidth" })
                                            </div>
                                        </div>
                                    </div>



                                </div>

                            </div>
                            <footer class="card-footer"></footer>
                        }
                    </div>

                </div>
            </div>
        }
    </section>

</div>

AgendaWeb/AgendaWeb/Views/Home/registrarse.cshtml
@model AgendaWeb.Models.Usuario

@{
    /**/
    ViewBag.Title = "registrarse";
}

<div class="container">
    @if (ViewBag.notificacion != null)
    {
        <div class="notification is-danger">
            @ViewBag.notificacion
        </div>

    }
    <section class="section">
        <div class="columns is-centered">
            <div class="column is-one-third">

                <div class="card">
                    <div class="has-background-primary">
                        <p class="title has-text-white" style="padding:30px;">Registrarse</p>
                    </div>
                    <div class="card-content">

                        @using (Html.BeginForm("registrarse", "Home", FormMethod.Post))
                        {
                            <div class="field">
                                @Html.Label("Email", new { @class = "label", })
                                <div class="control">
                                    @Html.EditorFor(Model => Model.usuario1, new { htmlAttributes = new { @class = "input", @type = "email", @id = "usuario1" } })
                                </div>
                            </div>

                            <div class="field">
                                @Html.Label("Confirmar Email", new { @class = "label", })
                                <div class="control">
                                    @Html.Editor("confEmail", new { htmlAttributes = new { @class = "input", @type = "email", @id = "confemail" } })
                                </div>
                            </div>

                            <div class="field">
                                @Html.Label("Contraseña", new { @class = "label" })
                                <div class="control">
                                    @Html.EditorFor(Model => Model.password, new { htmlAttributes = new { @class = "input", @type = "password", @id = "pass" } })
                                </div>
                            </div>
                            <div class="field">
                                @Html.Label("Confirmar Contraseña", new { @class = "label" })
                                <div class="control">
                                    @Html.Editor("confContrasena", new { htmlAttributes = new { @class = "input", @type = "password", @id = "confpass" } })
                                </div>
                            </div>

                            <div class="field">
                                <div class="control">
                                    <button type="submit" id="enviar" class="button is-primary is-fullwidth " disabled>Registrarse</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


@section scripts {
    <script>
    var cemail = false;
    var cpass = false;

    function removeDisabled() {
        if (cemail && cpass) {
            $('#enviar').removeAttr("disabled")
        } else {
            $('#enviar').attr("disabled")
        }
    }

        $('#usuario1').bind('input', function () {
        if ($(this).val() == $('#confemail').val() && $(this).val() != "") {
            $('#confemail').removeClass("is-danger")
            cemail = true;
        } else {
            $('#confemail').addClass("is-danger")
            cemail = false;
        }
        removeDisabled();
    })

    $('#pass').bind('input', function () {
        if ($(this).val() == $('#confpass').val() && $(this).val() != "") {
            $('#confpass').removeClass("is-danger")
            cpass = true;
        } else {
            $('#confpass').addClass("is-danger")
            cpass = false;
        }
        removeDisabled();
    })

    $('#confemail').bind('input', function () {

        if ($(this).val() == $('#usuario1').val() && $(this).val() != "") {
            $(this).removeClass("is-danger")
            cemail = true;
        } else {
            $(this).addClass("is-danger")
            cemail = false;
        }
        removeDisabled();
    })

    $('#confpass').bind('input', function () {

        if ($(this).val() == $('#pass').val() && $(this).val() != "") {
            $(this).removeClass("is-danger")
            cpass = true;
        } else {
            $(this).addClass("is-danger")
            cpass = false;
        }
        removeDisabled();
    })
    </script>
}